#include "assets/music/base.h"

const uint8_t wintergatan__marble_machine__voice_1[] PROGMEM = {
  MUSIC_BPM,    123,
  MUSIC_BEATS,  4,

  // BAR 1
  NOTE_E5,  QUARTER_NOTE_DOTTED,
  NOTE_B4,  EIGHTH_NOTE_TIE,
  NOTE_B4,  QUARTER_NOTE_DOTTED,
  NOTE_A4,  EIGHTH_NOTE,

  // BAR 2
  NOTE_G4,  EIGHTH_NOTE,
  NOTE_A4,  QUARTER_NOTE,
  NOTE_B4,  QUARTER_NOTE,
  NOTE_G4,  EIGHTH_NOTE,
  NOTE_A4,  EIGHTH_NOTE,
  NOTE_D5,  EIGHTH_NOTE_TIE,

  // BAR 3
  NOTE_D5,  QUARTER_NOTE_DOTTED,
  NOTE_B4,  EIGHTH_NOTE_TIE,
  NOTE_B4,  QUARTER_NOTE_DOTTED,
  NOTE_A4,  EIGHTH_NOTE,

  // BAR 4
  NOTE_G4,  EIGHTH_NOTE,
  NOTE_A4,  QUARTER_NOTE,
  NOTE_Fs4, QUARTER_NOTE,
  NOTE_G4,  EIGHTH_NOTE,
  NOTE_A4,  EIGHTH_NOTE,
  NOTE_D5,  EIGHTH_NOTE_TIE,

  // BAR 5
  NOTE_D5,  QUARTER_NOTE,
  EIGHTH_REST,
  NOTE_B4,  EIGHTH_NOTE_TIE,
  NOTE_B4,  QUARTER_NOTE_DOTTED,
  EIGHTH_REST,
  NOTE_A4,  EIGHTH_NOTE,

  // BAR 6
  NOTE_D5,  EIGHTH_NOTE,
  NOTE_C5,  QUARTER_NOTE,
  NOTE_B4,  QUARTER_NOTE,
  NOTE_A4,  EIGHTH_NOTE,
  NOTE_G4,  EIGHTH_NOTE,
  NOTE_A4,  EIGHTH_NOTE,
  
  // BAR 7
  NOTE_E4,  QUARTER_NOTE_DOTTED,
  NOTE_B4,  EIGHTH_NOTE,
  NOTE_B4,  QUARTER_NOTE,
  SIXTEENTH_REST,
  NOTE_D5,  EIGHTH_NOTE,
  
  // BAR 8
  NOTE_C5,  EIGHTH_NOTE,
  NOTE_B4,  EIGHTH_NOTE,
  NOTE_A4,  QUARTER_NOTE,
  NOTE_G4,  QUARTER_NOTE,
  NOTE_A4,  EIGHTH_NOTE,
  NOTE_E5,  EIGHTH_NOTE,

  MUSIC_END
};

const uint8_t* const wintergatan__marble_machine[] PROGMEM = {
  wintergatan__marble_machine__voice_1,
  music_sheet_end
};
