#include "assets/music/base.h"

const uint16_t sebastian_bach__bourree__config[] PROGMEM = {
  76, // BMP
  2,  // Beats
  2   // Voice count
};

const uint16_t sebastian_bach__bourree__right_hand[] PROGMEM = {
  NOTE_E5,  EIGHTH_NOTE,
  NOTE_Fs5, EIGHTH_NOTE,

  NOTE_G5,  QUARTER_NOTE,
  NOTE_Fs5, EIGHTH_NOTE,
  NOTE_E5,  EIGHTH_NOTE,
  NOTE_Ds5, QUARTER_NOTE,
  NOTE_E5,  EIGHTH_NOTE,
  NOTE_Fs5, EIGHTH_NOTE,

  NOTE_B4,  QUARTER_NOTE,
  NOTE_Cs5, EIGHTH_NOTE,
  NOTE_Ds5, EIGHTH_NOTE,
  NOTE_E5,  QUARTER_NOTE,
  NOTE_D5,  EIGHTH_NOTE,
  NOTE_C5,  EIGHTH_NOTE,

  NOTE_B4,  QUARTER_NOTE,
  NOTE_A4,  EIGHTH_NOTE,
  NOTE_G4,  EIGHTH_NOTE,
  NOTE_Fs4, QUARTER_NOTE,
  NOTE_G4,  EIGHTH_NOTE,
  NOTE_A4,  EIGHTH_NOTE,

  NOTE_B4,  EIGHTH_NOTE,
  NOTE_A4,  EIGHTH_NOTE,
  NOTE_G4,  EIGHTH_NOTE,
  NOTE_Fs4, EIGHTH_NOTE,
  NOTE_E4,  QUARTER_NOTE,
  NOTE_E5,  EIGHTH_NOTE,
  NOTE_Fs5, EIGHTH_NOTE,

  // Repeat

  // NOTE_G5,  QUARTER_NOTE,
  // NOTE_Fs5, EIGHTH_NOTE,
  // NOTE_E5,  EIGHTH_NOTE,
  // NOTE_Ds5, QUARTER_NOTE,
  // NOTE_E5,  EIGHTH_NOTE,
  // NOTE_Fs5, EIGHTH_NOTE,

  // NOTE_B4,  QUARTER_NOTE,
  // NOTE_Cs5, EIGHTH_NOTE,
  // NOTE_Ds5, EIGHTH_NOTE,
  // NOTE_E5,  QUARTER_NOTE,
  // NOTE_D5,  EIGHTH_NOTE,
  // NOTE_C5,  EIGHTH_NOTE,

  // NOTE_B4,  QUARTER_NOTE,
  // NOTE_A4,  EIGHTH_NOTE,
  // NOTE_G4,  EIGHTH_NOTE,
  // NOTE_Fs4, QUARTER_NOTE_DOTTED,
  // NOTE_G4,  EIGHTH_NOTE,
  // NOTE_G4,  HALF_NOTE,

  0,0
};

const uint16_t sebastian_bach__bourree__left_hand[] PROGMEM = {
  NOTE_G3,  EIGHTH_NOTE,
  NOTE_Fs3, EIGHTH_NOTE,

  NOTE_E3,  QUARTER_NOTE,
  NOTE_A3,  QUARTER_NOTE,
  NOTE_B3,  QUARTER_NOTE,
  NOTE_A3,  QUARTER_NOTE,

  NOTE_G3,  QUARTER_NOTE,
  NOTE_Fs3, QUARTER_NOTE,
  NOTE_E3,  QUARTER_NOTE,
  NOTE_Fs3, QUARTER_NOTE,

  NOTE_G3,  QUARTER_NOTE,
  NOTE_A3,  QUARTER_NOTE,
  NOTE_B3,  QUARTER_NOTE,
  NOTE_A3,  QUARTER_NOTE,

  NOTE_G3,  QUARTER_NOTE,
  NOTE_B3,  QUARTER_NOTE,
  NOTE_E3,  EIGHTH_NOTE,
  NOTE_Fs3, EIGHTH_NOTE,
  NOTE_G3,  EIGHTH_NOTE,
  NOTE_Fs3, EIGHTH_NOTE,

  0,0
};

const uint16_t* const sebastian_bach__bourree[] PROGMEM = {
  sebastian_bach__bourree__config,
  sebastian_bach__bourree__right_hand,
  sebastian_bach__bourree__left_hand
};
