#include "assets/music/base.h"

static const uint8_t sebastian_bach__bourree__right_hand[] PROGMEM = {
  MUSIC_BPM,    76,
  MUSIC_BEATS,  2,

  REPEAT_START, 2,

    NOTE_E5,  EIGHTH_NOTE,
    NOTE_Fs5, EIGHTH_NOTE,

    NOTE_G5,  QUARTER_NOTE,
    NOTE_Fs5, EIGHTH_NOTE,
    NOTE_E5,  EIGHTH_NOTE,
    NOTE_Ds5, QUARTER_NOTE,
    NOTE_E5,  EIGHTH_NOTE,
    NOTE_Fs5, EIGHTH_NOTE,

    NOTE_B4,  QUARTER_NOTE,
    NOTE_Cs5, EIGHTH_NOTE,
    NOTE_Ds5, EIGHTH_NOTE,
    NOTE_E5,  QUARTER_NOTE,
    NOTE_D5,  EIGHTH_NOTE,
    NOTE_C5,  EIGHTH_NOTE,

    //

    NOTE_B4,  QUARTER_NOTE,
    NOTE_A4,  EIGHTH_NOTE,
    NOTE_G4,  EIGHTH_NOTE,
    NOTE_Fs4, QUARTER_NOTE,
    NOTE_G4,  EIGHTH_NOTE,
    NOTE_A4,  EIGHTH_NOTE,

    NOTE_B4,  EIGHTH_NOTE,
    NOTE_A4,  EIGHTH_NOTE,
    NOTE_G4,  EIGHTH_NOTE,
    NOTE_Fs4, EIGHTH_NOTE,
    NOTE_E4,  QUARTER_NOTE,
    NOTE_E5,  EIGHTH_NOTE,
    NOTE_Fs5, EIGHTH_NOTE,

    //

    NOTE_G5,  QUARTER_NOTE,
    NOTE_Fs5, EIGHTH_NOTE,
    NOTE_E5,  EIGHTH_NOTE,
    NOTE_Ds5, QUARTER_NOTE,
    NOTE_E5,  EIGHTH_NOTE,
    NOTE_Fs5, EIGHTH_NOTE,

    NOTE_B4,  QUARTER_NOTE,
    NOTE_Cs5, EIGHTH_NOTE,
    NOTE_Ds5, EIGHTH_NOTE,
    NOTE_E5,  QUARTER_NOTE,
    NOTE_D5,  EIGHTH_NOTE,
    NOTE_C5,  EIGHTH_NOTE,

    //

    NOTE_B4,  QUARTER_NOTE,
    NOTE_A4,  EIGHTH_NOTE,
    NOTE_G4,  EIGHTH_NOTE_TIE,
    NOTE_Fs4, SIXTEENTH_NOTE_TIE,
    NOTE_G4,  SIXTEENTH_NOTE_TIE,
    NOTE_Fs4, SIXTEENTH_NOTE_TIE,
    NOTE_G4,  SIXTEENTH_NOTE_TIE,
    NOTE_Fs4, EIGHTH_NOTE_TIE,
    NOTE_G4,  EIGHTH_NOTE,

    NOTE_G4,  HALF_NOTE_DOTTED,

  REPEAT_END,
  REPEAT_START, 2,

    NOTE_B4,  EIGHTH_NOTE,
    NOTE_G4,  EIGHTH_NOTE,

    NOTE_D5,  QUARTER_NOTE,
    NOTE_A4,  EIGHTH_NOTE,
    NOTE_C5,  EIGHTH_NOTE,
    NOTE_B4,  QUARTER_NOTE,
    NOTE_G5,  EIGHTH_NOTE,
    NOTE_D5,  EIGHTH_NOTE,

    NOTE_E5,  QUARTER_NOTE,
    NOTE_B4,  EIGHTH_NOTE,
    NOTE_D5,  EIGHTH_NOTE,
    NOTE_C5,  QUARTER_NOTE,
    NOTE_B4,  EIGHTH_NOTE,
    NOTE_A4,  EIGHTH_NOTE,
    
    NOTE_Gs4, QUARTER_NOTE,
    NOTE_A4,  EIGHTH_NOTE,
    NOTE_B4,  EIGHTH_NOTE,
    NOTE_C5,  QUARTER_NOTE,
    NOTE_B4,  EIGHTH_NOTE,
    NOTE_A4,  EIGHTH_NOTE,
    
    NOTE_A4,  HALF_NOTE_DOTTED,
    NOTE_D5,  EIGHTH_NOTE,
    NOTE_A4,  EIGHTH_NOTE,
    
    NOTE_B4,  QUARTER_NOTE,
    NOTE_G5,  EIGHTH_NOTE,
    NOTE_D5,  EIGHTH_NOTE,
    NOTE_E5,  QUARTER_NOTE,
    NOTE_B4,  EIGHTH_NOTE,
    NOTE_D5,  EIGHTH_NOTE,

    NOTE_C5,  QUARTER_NOTE,
    NOTE_A4,  EIGHTH_NOTE,
    NOTE_E5,  EIGHTH_NOTE,
    NOTE_Fs5, QUARTER_NOTE,
    NOTE_Cs5, EIGHTH_NOTE,
    NOTE_E5,  EIGHTH_NOTE,

    NOTE_D5,  QUARTER_NOTE,
    NOTE_Cs5, EIGHTH_NOTE,
    NOTE_B4,  EIGHTH_NOTE,
    NOTE_As4, QUARTER_NOTE_DOTTED,
    NOTE_B4,  EIGHTH_NOTE,

    NOTE_B4,  HALF_NOTE_DOTTED,
    NOTE_B5,  EIGHTH_NOTE,
    NOTE_Fs5, EIGHTH_NOTE,

    NOTE_Gs5, QUARTER_NOTE,
    NOTE_Fs5, EIGHTH_NOTE,
    NOTE_E5,  EIGHTH_NOTE,
    NOTE_A5,  QUARTER_NOTE,
    NOTE_E5,  EIGHTH_NOTE,
    NOTE_G5, EIGHTH_NOTE,

    NOTE_Fs5, QUARTER_NOTE,
    NOTE_E5,  EIGHTH_NOTE,
    NOTE_D5,  EIGHTH_NOTE,
    NOTE_G5,  QUARTER_NOTE,
    NOTE_D5,  EIGHTH_NOTE,
    NOTE_Fs5, EIGHTH_NOTE,

    NOTE_E5,  QUARTER_NOTE,
    NOTE_A5,  EIGHTH_NOTE,
    NOTE_E5,  EIGHTH_NOTE,
    NOTE_Fs5, QUARTER_NOTE,
    NOTE_Cs5, EIGHTH_NOTE,
    NOTE_E5,  EIGHTH_NOTE,

    NOTE_Ds5, QUARTER_NOTE,
    NOTE_B4,  HALF_NOTE,
    NOTE_E5,  EIGHTH_NOTE,
    NOTE_B4,  EIGHTH_NOTE,

    NOTE_C5,  QUARTER_NOTE,
    NOTE_D5,  EIGHTH_NOTE,
    NOTE_A4,  EIGHTH_NOTE,
    NOTE_B4,  QUARTER_NOTE,
    NOTE_C5,  EIGHTH_NOTE,
    NOTE_G4,  EIGHTH_NOTE,

    NOTE_A4,  QUARTER_NOTE,
    NOTE_B4,  EIGHTH_NOTE,
    NOTE_Fs4, EIGHTH_NOTE,
    NOTE_G4,  QUARTER_NOTE,
    NOTE_Fs4, EIGHTH_NOTE,
    NOTE_E4,  EIGHTH_NOTE,

    NOTE_Ds4, QUARTER_NOTE,
    NOTE_E4,  EIGHTH_NOTE,
    NOTE_Fs4, EIGHTH_NOTE,
    NOTE_G4,  EIGHTH_NOTE,
    NOTE_Fs4, SIXTEENTH_NOTE_TIE,
    NOTE_G4,  SIXTEENTH_NOTE_TIE,
    NOTE_Fs4, EIGHTH_NOTE,
    NOTE_E4,  EIGHTH_NOTE,

    NOTE_E4,  HALF_NOTE_DOTTED,

  REPEAT_END,

  0,0
};

static const uint8_t sebastian_bach__bourree__left_hand[] PROGMEM = {
  REPEAT_START, 2,

    NOTE_G3,  EIGHTH_NOTE,
    NOTE_Fs3, EIGHTH_NOTE,

    NOTE_E3,  QUARTER_NOTE,
    NOTE_A3,  QUARTER_NOTE,
    NOTE_B3,  QUARTER_NOTE,
    NOTE_A3,  QUARTER_NOTE,

    NOTE_G3,  QUARTER_NOTE,
    NOTE_Fs3, QUARTER_NOTE,
    NOTE_E3,  QUARTER_NOTE,
    NOTE_Fs3, QUARTER_NOTE,

    NOTE_G3,  QUARTER_NOTE,
    NOTE_A3,  QUARTER_NOTE,
    NOTE_B3,  QUARTER_NOTE,
    NOTE_A3,  QUARTER_NOTE,

    NOTE_G3,  QUARTER_NOTE,
    NOTE_B3,  QUARTER_NOTE,
    NOTE_E3,  EIGHTH_NOTE,
    NOTE_Fs3, EIGHTH_NOTE,
    NOTE_G3,  EIGHTH_NOTE,
    NOTE_Fs3, EIGHTH_NOTE,

    NOTE_E3, QUARTER_NOTE,
    NOTE_A3, QUARTER_NOTE,
    NOTE_B3, QUARTER_NOTE,
    NOTE_A3, QUARTER_NOTE,

    NOTE_G3, QUARTER_NOTE,
    NOTE_Fs3, QUARTER_NOTE,
    NOTE_E3, QUARTER_NOTE,
    NOTE_Fs3, QUARTER_NOTE,
    
    NOTE_G3, QUARTER_NOTE,
    NOTE_C4, QUARTER_NOTE,
    NOTE_D4, QUARTER_NOTE,
    NOTE_D3, QUARTER_NOTE,
    
    NOTE_G3, HALF_NOTE_DOTTED,

  REPEAT_END,
  REPEAT_START, 2,
  
    NOTE_G3,  QUARTER_NOTE,
    NOTE_Fs3, QUARTER_NOTE,
    NOTE_D3,  QUARTER_NOTE,
    NOTE_G3,  QUARTER_NOTE,
    NOTE_B3,  QUARTER_NOTE,
    
    NOTE_C4,  QUARTER_NOTE,
    NOTE_Gs3, QUARTER_NOTE,
    NOTE_A3,  QUARTER_NOTE,
    NOTE_D4,  QUARTER_NOTE,
    
    NOTE_E4,  QUARTER_NOTE,
    NOTE_A3,  QUARTER_NOTE,
    NOTE_E4,  QUARTER_NOTE,
    NOTE_E3,  QUARTER_NOTE,
    
    NOTE_A3,  EIGHTH_NOTE,
    NOTE_B3,  EIGHTH_NOTE,
    NOTE_A3,  EIGHTH_NOTE,
    NOTE_G3,  EIGHTH_NOTE,
    NOTE_Fs3, QUARTER_NOTE,
    NOTE_D3,  QUARTER_NOTE,
    
    NOTE_G3,  QUARTER_NOTE,
    NOTE_B3,  QUARTER_NOTE,
    NOTE_C4,  QUARTER_NOTE,
    NOTE_Gs3, QUARTER_NOTE,

    NOTE_A3,  QUARTER_NOTE,
    NOTE_Cs4, QUARTER_NOTE,
    NOTE_D4,  QUARTER_NOTE,
    NOTE_As3, QUARTER_NOTE,
    
    NOTE_B3,  QUARTER_NOTE,
    NOTE_E4,  QUARTER_NOTE,
    NOTE_Fs4, QUARTER_NOTE,
    NOTE_Fs3, QUARTER_NOTE,
    
    NOTE_B3,  EIGHTH_NOTE,
    NOTE_As3, EIGHTH_NOTE,
    NOTE_B3,  EIGHTH_NOTE,
    NOTE_Cs4, EIGHTH_NOTE,
    NOTE_Ds4, QUARTER_NOTE,
    NOTE_B3,  QUARTER_NOTE,

    NOTE_E4,  QUARTER_NOTE,
    NOTE_D4,  QUARTER_NOTE,
    NOTE_C4,  QUARTER_NOTE,
    NOTE_A3,  QUARTER_NOTE,
    
    NOTE_D4,  QUARTER_NOTE,
    NOTE_C4,  QUARTER_NOTE,
    NOTE_B3,  QUARTER_NOTE,
    NOTE_G3,  QUARTER_NOTE,
    
    NOTE_C4,  QUARTER_NOTE,
    NOTE_B3,  QUARTER_NOTE,
    NOTE_A3,  QUARTER_NOTE,
    NOTE_Fs3, QUARTER_NOTE,

    NOTE_B3,  QUARTER_NOTE_DOTTED,
    NOTE_C4,  EIGHTH_NOTE,
    NOTE_B3,  EIGHTH_NOTE,
    NOTE_A3,  EIGHTH_NOTE,
    NOTE_Gs3, QUARTER_NOTE,
    
    NOTE_A3,  EIGHTH_NOTE,
    NOTE_E4,  EIGHTH_NOTE,
    NOTE_Fs4, QUARTER_NOTE,
    NOTE_G3,  EIGHTH_NOTE,
    NOTE_Ds4, EIGHTH_NOTE,
    NOTE_E4,  QUARTER_NOTE,
    
    NOTE_Fs3, EIGHTH_NOTE,
    NOTE_Cs4, EIGHTH_NOTE,
    NOTE_Ds4, QUARTER_NOTE,
    NOTE_E3,  QUARTER_NOTE,
    NOTE_A3,  QUARTER_NOTE,
    
    NOTE_B3,  QUARTER_NOTE,
    NOTE_A3,  QUARTER_NOTE,
    NOTE_B3,  HALF_NOTE,

    NOTE_E3,  HALF_NOTE_DOTTED,

  REPEAT_END,

  MUSIC_END
};

const uint8_t* const sebastian_bach__bourree[] PROGMEM = {
  sebastian_bach__bourree__right_hand,
  sebastian_bach__bourree__left_hand,
  music_sheet_end
};
