
// Seven segments scroll concept
// TODO: Learn text scroll -> https://www.arduinoecia.com.br/arduino-como-realizar-um-scroll-no-lcd/
delay(1000);
disp_setCursor(0);
disp_print("    ");
delay(500);
disp_setCursor(0);
disp_print("   D");
delay(500);
disp_setCursor(0);
disp_print("  DA");
delay(500);
disp_setCursor(0);
disp_print(" DAV");
delay(500);
disp_setCursor(0);
disp_print("DAVI");
delay(500);
disp_setCursor(0);
disp_print("AVI ");
delay(500);
disp_setCursor(0);
disp_print("VI I");
delay(500);
disp_setCursor(0);
disp_print("I IN");
delay(500);
disp_setCursor(0);
disp_print(" INA");
delay(500);
disp_setCursor(0);
disp_print("INAC");
delay(500);
disp_setCursor(0);
disp_print("NACI");
delay(500);
disp_setCursor(0);
disp_print("ACIO");
delay(500);
disp_setCursor(0);
disp_print("CIO ");
delay(500);
disp_setCursor(0);
disp_print("IO  ");
delay(500);
disp_setCursor(0);
disp_print("O   ");
delay(500);
disp_setCursor(0);
disp_print("    ");
delay(500);
