#include "assets/music/base.h"

const uint16_t unknown__la_cucaracha[] PROGMEM = {
  131,  // BMP
  2,    // Beats

  // First part

  NOTE_C5,  EIGHTH_NOTE,
  NOTE_C5,  EIGHTH_NOTE,
  NOTE_C5,  EIGHTH_NOTE,
  NOTE_F5,  QUARTER_DOTTED_NOTE,
  NOTE_A5,  QUARTER_NOTE,

  NOTE_C5,  EIGHTH_NOTE,
  NOTE_C5,  EIGHTH_NOTE,
  NOTE_C5,  EIGHTH_NOTE,
  NOTE_F5,  QUARTER_DOTTED_NOTE,
  NOTE_A5,  HALF_DOTTED_NOTE,

  NOTE_F5,  QUARTER_NOTE,
  NOTE_F5,  EIGHTH_NOTE,
  NOTE_E5,  EIGHTH_NOTE,
  NOTE_E5,  EIGHTH_NOTE,
  NOTE_D5,  EIGHTH_NOTE,
  NOTE_D5,  EIGHTH_NOTE,
  NOTE_C5,  HALF_DOTTED_NOTE,

  // Second part

  NOTE_C5,  EIGHTH_NOTE,
  NOTE_C5,  EIGHTH_NOTE,
  NOTE_C5,  EIGHTH_NOTE,
  NOTE_E5,  QUARTER_DOTTED_NOTE,
  NOTE_G5,  QUARTER_NOTE,

  NOTE_C5,  EIGHTH_NOTE,
  NOTE_C5,  EIGHTH_NOTE,
  NOTE_C5,  EIGHTH_NOTE,
  NOTE_E5,  QUARTER_DOTTED_NOTE,
  NOTE_G5,  HALF_DOTTED_NOTE,

  NOTE_C6,  QUARTER_NOTE,
  NOTE_D6,  EIGHTH_NOTE,
  NOTE_C6,  EIGHTH_NOTE,
  NOTE_As5, EIGHTH_NOTE,
  NOTE_A5,  EIGHTH_NOTE,
  NOTE_G5,  EIGHTH_NOTE,
  NOTE_F5,  HALF_DOTTED_NOTE,

  0,0
};
